import Head from "next/head";
import styles from "@/styles/Home.module.css"
import Link from "next/link";
import React, { useRef, useState } from 'react';
// Import Swiper React components
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/css';
import 'swiper/css/pagination';

import { Pagination } from 'swiper/modules';

export default function Home() {
  return (
    <>
      <Head>
        <title>Kenali Diri</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.banner}>
        <div className={styles.divider}></div>
        <div className={styles.banner_text}>
          <h1><span>Kenali Dirimu</span>,<br/> Raih Masa Depan Gemilang!</h1>
          <p>Yuk temukan potensi terbesar dirimu dan petakan masa depanmu dengan maksimal</p>
          <div className={styles.banner_btn}>
            <Link href=""><button>Mulai Sekarang</button></Link>
            <Link href=""><button>Jadwalkan Pertemuan</button></Link>
          </div>
        </div>
        <img src="images/setting-banner.png" alt="Kenali Diri Sekolah" className={styles.setting_banner}/>
        <img src="images/medals-banner.png" alt="Kenali Diri Sekolah" className={styles.medals_banner}/>
        <img src="images/book-banner.png" alt="Kenali Diri Sekolah" className={styles.book_banner}/>
        <img src="images/man_banner.png" alt="Kenali Diri" className={styles.man_banner}/>
      </div>
      <div className={styles.section1}>
        <h1 className={styles.heading_home}><span>-</span> Kenali Dirimu pada</h1>
        <div className={styles.section1_layout}>
          <div className={styles.section1_box}>
              <img src="images/sekolah.png" alt="Kenali Diri di Sekolah" />
              <h5>Sekolah</h5>
              <Link href='#'><button>Selengkapnya</button></Link>
          </div>
          <div className={styles.section1_box}>
              <img src="images/perusahaan.png" alt="Kenali Diri di Sekolah" />
              <h5>Perusahaan</h5>
              <Link href='#'><button>Selengkapnya</button></Link>
          </div>
          <div className={styles.section1_box}>
              <img src="images/campus.png" alt="Kenali Diri di Sekolah" />
              <h5>Kampus</h5>
              <Link href='#'><button>Selengkapnya</button></Link>
          </div>
          <div className={styles.section1_box}>
              <img src="images/people.png" alt="Kenali Diri di Sekolah" />
              <h5>Keluarga</h5>
              <Link href='#'><button>Selengkapnya</button></Link>
          </div>
        </div>
      </div>
      <div className={styles.section2}>
        <h1 className={styles.heading_home}><span>-</span> Tes Gratis Sekarang</h1>
        <div className={styles.form_box}>
          <form>
            <div className={styles.form_box_layout}>
              <input type="text" placeholder="Nama Lengkap"/>
              <input type="text" placeholder="Alamat Email"/>
              <input type="text" placeholder="Nomor Whatsapp"/>
            </div>
            <button>Jadwalkan Sekarang</button>
          </form>
        </div>
      </div>
      <div className={styles.section3}>
        <div className={styles.section3_img}>
          <img src="images/section-3-img.png" alt="Kenali Diri" />
        </div>
        <div className={styles.section3_text}>
          <h1>Langkah Awal untuk <span>Mengenal</span> Diri Sendiri</h1>
          <p>Konsultasi Personal untuk Menggapai Masa Depan yang Lebih Baik</p>
          <Link href="/"><button>Konsultasi Sekarang</button></Link>
        </div>
        <div className={styles.divider}></div>
      </div>
      <div className={styles.video}>
        <video src="video/video.mp4" autoPlay loop muted></video>
        <div className={styles.divider}></div>
      </div>
      <div className={styles.section1}>
        <h1 className={styles.heading_home}><span>-</span> Artikel Kami</h1>
        <Swiper
          slidesPerView={4}
          spaceBetween={0}
          pagination={{
            clickable: true,
          }}
          modules={[Pagination]}
          className="mySwiper"
        >
          <SwiperSlide>
            <div className={styles.section1_box}>
                <div className={styles.images_article}>
                  <img src="images/article_image.png" alt="Artikel Kenali Diri" />
                </div>
                <div className={styles.content_article}>
                  <h3>Tips Mengelola Emosi dan Stres dengan Mengenali Diri Sendiri</h3>
                  <p>Lorem Ipsum is simply dummy text of the printing and is simply dummy</p>
                </div>
                <Link href='#'><button>Selengkapnya</button></Link>
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div className={styles.section1_box}>
                <div className={styles.images_article}>
                  <img src="images/article_image.png" alt="Artikel Kenali Diri" />
                </div>
                <div className={styles.content_article}>
                  <h3>Tips Mengelola Emosi dan Stres dengan Mengenali Diri Sendiri</h3>
                  <p>Lorem Ipsum is simply dummy text of the printing and is simply dummy</p>
                </div>
                <Link href='#'><button>Selengkapnya</button></Link>
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div className={styles.section1_box}>
                <div className={styles.images_article}>
                  <img src="images/article_image.png" alt="Artikel Kenali Diri" />
                </div>
                <div className={styles.content_article}>
                  <h3>Tips Mengelola Emosi dan Stres dengan Mengenali Diri Sendiri</h3>
                  <p>Lorem Ipsum is simply dummy text of the printing and is simply dummy</p>
                </div>
                <Link href='#'><button>Selengkapnya</button></Link>
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div className={styles.section1_box}>
                <div className={styles.images_article}>
                  <img src="images/article_image.png" alt="Artikel Kenali Diri" />
                </div>
                <div className={styles.content_article}>
                  <h3>Tips Mengelola Emosi dan Stres dengan Mengenali Diri Sendiri</h3>
                  <p>Lorem Ipsum is simply dummy text of the printing and is simply dummy</p>
                </div>
                <Link href='#'><button>Selengkapnya</button></Link>
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div className={styles.section1_box}>
                <div className={styles.images_article}>
                  <img src="images/article_image.png" alt="Artikel Kenali Diri" />
                </div>
                <div className={styles.content_article}>
                  <h3>Tips Mengelola Emosi dan Stres dengan Mengenali Diri Sendiri</h3>
                  <p>Lorem Ipsum is simply dummy text of the printing and is simply dummy</p>
                </div>
                <Link href='#'><button>Selengkapnya</button></Link>
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div className={styles.section1_box}>
                <div className={styles.images_article}>
                  <img src="images/article_image.png" alt="Artikel Kenali Diri" />
                </div>
                <div className={styles.content_article}>
                  <h3>Tips Mengelola Emosi dan Stres dengan Mengenali Diri Sendiri</h3>
                  <p>Lorem Ipsum is simply dummy text of the printing and is simply dummy</p>
                </div>
                <Link href='#'><button>Selengkapnya</button></Link>
            </div>
          </SwiperSlide>
          <SwiperSlide>
            <div className={styles.section1_box}>
                <div className={styles.images_article}>
                  <img src="images/article_image.png" alt="Artikel Kenali Diri" />
                </div>
                <div className={styles.content_article}>
                  <h3>Tips Mengelola Emosi dan Stres dengan Mengenali Diri Sendiri</h3>
                  <p>Lorem Ipsum is simply dummy text of the printing and is simply dummy</p>
                </div>
                <Link href='#'><button>Selengkapnya</button></Link>
            </div>
          </SwiperSlide>
        </Swiper>
      </div>
    </>
  );
}
